run only storybook package for storybook
Soil-labs/eden-app-2-FrontEnd pull request #716
Opened 2022-12-14 01:19 UTC by with-heart

This PR replaces our use of `turbo` with just `yarn workspace storybook` so we can make sure it's only running a single instance.

2022-12-14 01:19 UTC, with-heart commented on apps/storybook/package.json
> -    "storybook": "start-storybook -p 6006 --no-manager-cache",
Do we actually need to disable the manager cache here?

2022-12-15 11:46 UTC, e-roy requested changes
Initial setup of this project I was forcing storybook through turbo because I believed at the time turbo would provide faster performance over the long term when more stories were added.  I'm not noticing a change in speed between the two with 150+ stories.

2022-12-15 11:46 UTC, e-roy commented on apps/storybook/package.json
> -    "storybook": "start-storybook -p 6006 --no-manager-cache",
I think at the time when I initially set up this build I was testing between the scripts in this file `storybook` and `sb`.  I believe this disable is here because I was trying to force storybook run through turbo.  If the disabled cache isn't done in the [turbo.json](https://github.com/Soil-labs/eden-app-2-FrontEnd/blob/36607a36d6bea3c2ef981c3b7020bd2116121909/turbo.json#L37) file, then I believe it needs to be done here.

Since this PR will bypass using turbo with storybook, I'm not seeing a use for this script command to even be here.  This line can just be deleted since it is leftover from initial setup

2022-12-21 20:56 UTC, e-roy approved these changes

2022-12-21 20:57 UTC, merged