clean up jest config and testing stuff
Soil-labs/eden-app-2-FrontEnd pull request #720
Opened 2022-12-15 00:16 UTC by with-heart

This PR consolidates our `jest` config in a new `jest-presets` package (mostly by following one of the `turbo` example repos). This gives us a single place to implement and document our shared `jest` shit which will hopefully make it easier to manage moving forward.

Adding `jest` to a package in the monorepo now just requires installing `jest-presets` and adding one line of `jest` configuration to `jest.config.ts`

---

Still using `@swc/jest` for the speed

Also moved test-related `dependencies` to the root `package.json` since those are made global by `yarn`. No need to specify them in every package.

2022-12-15 00:20 UTC, with-heart commented on package.json
> +  },
We can just house all global dev dependencies under `dependencies` in the root `package.json`. The distinction between `dependencies`/`devDependencies` doesn't matter for the root since it's a `private` package.

2022-12-15 00:22 UTC, with-heart commented on packages/config/jest/setup.ts
> -});
I removed these but wanted to double-check and make sure that's fine. We shouldn't need to do this

2022-12-15 00:26 UTC, with-heart commented on packages/config/jest/setup.ts
> -Date.now = jest.fn(() => new Date(Date.UTC(2022, 1, 1)).valueOf());
We should remove this in favor of mocking it locally in suites/tests. It's likely that mocking `Date.now` won't be the majority use case for our tests

2022-12-15 00:31 UTC, with-heart commented on packages/jest-presets/jest/jsdom/jest-preset.js
> +  setupFilesAfterEnv: [path.resolve(__dirname, "./jest-setup.ts")],
Since the `jest-setup.ts` file is in the `jest-presets` package and the package is used from another package (in the package's `jest.config.ts` file), specifying the relative path of `./jest-setup.ts` here won't work.

`jest` will load the preset and look for `jest-setup.ts` in the package's directory where it doesn't exist

`path.resolve` with `__dirname` allows us to point to the file _relative to_ `jest-preset.js`. When `jest` loads the preset, it will find it in the correct place

2022-12-15 00:31 UTC, with-heart commented on packages/ui/jest.config.ts
> +};
🔥

2022-12-15 11:55 UTC, e-roy requested changes

2022-12-15 11:55 UTC, e-roy commented on packages/jest-presets/package.json
> +  "name": "jest-presets",
can you use  `"name": "@eden/package-jest-presets",` instead please

2022-12-15 11:55 UTC, e-roy commented on packages/ui/package.json
> +    "jest-presets": "*",
`"@eden/package-jest-presets": "*"` to keep consistency for packages within this repo please

2022-12-21 20:58 UTC, e-roy approved these changes

2022-12-21 20:59 UTC, merged